spring:
  datasource:
    database-plataform: postgres
    url: jdbc:postgresql://localhost:5438/hobby_keeping
    username: postgres
    password: postgres
  data:
    web:
      pageable:
        max-page-size: 100
  jpa:
    database: POSTGRESQL
    database-plataform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: "xO5E6vPqB0d8eC4jnavI3OHOHgbqQkwlOkYrhVoAm1Xnm8T9sdlVsfcMerFsLU6uY17tcUlH/IILjGo2DHr9O0ggAE52UvG4YZVhhcIANDeMBUhHV4+tEx4PT9NkxdiYJXyP3nJzZGJ9ElfwerhXdmJwXxXGn01YXt135jGjGryEGWIPxHARXUCIqMyzxSPFIPiJ+4jyYdQ+AeONkSDZ2P3CoXsQ37ZCQhUjTA=="
  token-expiration-minutes: 30

