CREATE TABLE authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   created_at TIMESTAMP with time zone,
   updated_at TIMESTAMP with time zone,
   CONSTRAINT pk_authors PRIMARY KEY (id)
);