CREATE TABLE books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR NOT NULL,
   num_pages BIGINT NOT NULL,
   genre VARCHAR NOT NULL,
   serie VARCHAR,
   publish_date date NOT NULL,
   author_id BIGINT NOT NULL,
   created_at TIMESTAMP with time zone,
   updated_at TIMESTAMP with time zone,
   CONSTRAINT pk_books PRIMARY KEY (id)
);

ALTER TABLE books ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);