CREATE TABLE reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT,
   book_id BIGINT,
   start_date TIMESTAMP with time zone NOT NULL,
   end_date TIMESTAMP with time zone,
   did_not_finished BOOLEAN,
   created_at TIMESTAMP with time zone,
   updated_at TIMESTAMP with time zone,
   CONSTRAINT pk_reads PRIMARY KEY (id)
);

ALTER TABLE reads ADD CONSTRAINT FK_READS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE reads ADD CONSTRAINT FK_READS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);